import type { Metadata } from 'next'
import { Inter, Kalam } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const kalam = Kalam({
  subsets: ['latin'],
  weight: '300',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={kalam.className}>{children}</body>
    </html>
  )
}
